
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      PORT: ${PORT}
    ports:
      - "${PORT}:8080"
    restart: unless-stopped

volumes:
  db_data:
